version: '3.8'

services:
  bot-service:
    image: anas1005/instruvibes:bot-service
    depends_on:
      - redis
    volumes:
      - shared_audio:/usr/src/app/shared
    ports:
      - "3000:3000"
    env_file:
      - .env

  search-service:
    image: anas1005/instruvibes:search-service
    depends_on:
      - redis
    ports:
      - "3002:3002"
    env_file:
      - .env

  converter-service:
    image: anas1005/instruvibes:converter-service
    depends_on:
      - redis
    volumes:
      - shared_audio:/usr/src/app/shared
    ports:
      - "3001:3001"
    env_file:
      - .env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  shared_audio:
    driver: local