version: '3.8'

services:
  auth-service:
    image: ddev2636/campus-cart:auth-service
    ports:
      - "5001:5001"
    env_file:
      - .env

  product-service:
    image: ddev2636/campus-cart:product-service
    ports:
      - "5000:5000"
    env_file:
      - .env
      
