version: '3.8'
services:
  auth-service:
    build:
      context: .
      dockerfile: authService/Dockerfile
    ports:
      - "5001:5001" # Map auth-service port to host

  product-service:
    build:
      context: .
      dockerfile: productService/Dockerfile
    ports:
      - "5000:5000" # Map product-service port to host
