name: CD Pipeline

on:
  push:
    branches:
      - main # Adjust to your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push auth-service image
        id: auth-service
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./authService/Dockerfile
          push: true
          tags: ddev2636/campus-cart:auth-service

      - name: Build and push product-service image
        id: product-service
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./productService/Dockerfile
          push: true
          tags: ddev2636/campus-cart:product-service
