name: CD Pipeline

on:
  push:
    branches:
      - main # Adjust to your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push auth-service image
        id: auth-service
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./authService/Dockerfile
          push: true
          tags: ddev2636/campus-cart:auth-service

      - name: Build and push product-service image
        id: product-service
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./productService/Dockerfile
          push: true
          tags: ddev2636/campus-cart:product-service

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Ensure Docker is running
            sudo systemctl start docker
            sudo systemctl enable docker

            cd /home/ubuntu/campus-cart-backend
            sudo docker-compose -f docker-compose.prod.yml down  # Stop and remove current containers
            sudo docker system prune -a -f  # Clean up unused Docker objects
            sudo docker-compose -f docker-compose.prod.yml pull  # Pull latest images
            sudo docker-compose -f docker-compose.prod.yml up -d  # Start new containers
